---
title: 'Smoking Cessation: Logistic Regression'
author: "Zoë E. Laky"
date: '20250603'
output:
  pdf_document: default
  html_notebook: default
---

## Installing & Loading Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/LV/Final_Data")

required_packages <- c(
  'tidyverse', 'caret', 'visdat', 'moments', 'arsenal', 'ranger',
  'sjPlot', 'sjmisc', 'parameters', 'DataExplorer', 'car', 'naniar', 'recipes', 'kernlab', 'PRROC', 'ggplot2',
  'dplyr', 'tidyr' 
)

#install new packages
new_packages <- setdiff(required_packages, rownames(installed.packages()))
if (length(new_packages)) install.packages(new_packages)

#load packages
invisible(lapply(required_packages, require, character.only = TRUE))

#citations
sapply(c("tidyverse", "caret", "sjPlot"), citation)

#working directory
cat("Working Directory:", getwd(), "\n")
sessionInfo()

rm(required_packages, new_packages)
```

## Seed
```{r}
#testing seed 
seed <- 842
set.seed(seed)
rnorm(1) #1.377664
exists(".Random.seed")
.Random.seed
set.seed(NULL)
```

## Importance Function
```{r}
auprc_feature_importance <- function(model, data, target_col, positive_class = "yes") {
  y_true <- as.character(data[[target_col]])  #observed labels and predicted probabilities
  predictors <- data %>% select(-all_of(target_col))
  probs <- predict(model, newdata = predictors, type = "prob")[, positive_class] #baseline predicted probabilities for positive class
  fg <- probs[y_true == positive_class] #predicted probabilities for the positive class
  bg <- probs[y_true != positive_class] #predicted probabilities for the negative class
  baseline_auprc <- pr.curve(scores.class0 = fg, scores.class1 = bg)$auc.integral
  
  importance <- sapply(names(predictors), function(var) {
    data_permuted <- predictors
    data_permuted[[var]] <- sample(data_permuted[[var]]) #permute the variable

    if (is.factor(data[[var]])) { #preserve factor structure
      data_permuted[[var]] <- factor(data_permuted[[var]], levels = levels(data[[var]]))
    }
    
    perm_probs <- predict(model, newdata = data_permuted, type = "prob")[, positive_class]
    fg_perm <- perm_probs[y_true == positive_class]
    bg_perm <- perm_probs[y_true != positive_class]
    perm_auprc <- pr.curve(scores.class0 = fg_perm, scores.class1 = bg_perm)$auc.integral
    
    baseline_auprc - perm_auprc  #drop in AUPRC = importance
  })
  
  tibble(feature = names(importance), auprc_drop = importance) %>%
    arrange(desc(auprc_drop))
} 
#NOTE: Importance drop measure is "aggregated" across all dummy variables derived from original variables.
```

## Loading Data
```{r}
read_clean <- function(file_path) {
  df <- read.csv(file_path, header = TRUE, na.strings = c("", "NA"), stringsAsFactors = TRUE)
  df[df == "NA"] <- NA  
  return(df)
}

cessationtrain_p05_final <- read_clean("cessationtrain_p05_final.csv")
cessationtest_p05_final <- read_clean("cessationtest_p05_final.csv")

df_list <- list(
  p05_train  = cessationtrain_p05_final, 
  p05_test   = cessationtest_p05_final
)

df_list <- lapply(df_list, function(df) {
  df %>%
    arrange(ID) %>%
    mutate(row_id = row_number())
})

cessationtrain_p05_final <- df_list$p05_train
cessationtest_p05_final <- df_list$p05_test

rm(df_list)
```

## Variable Types
```{r}
factor_vars_p05 <- c("QuA1Rc", "Cig7", "ContemplationStatus", "EducationRc", 
                     "SoC2BRc", "SoC5BRc", "SSEQ6BRc", "SSEQ8BRc", "SSS17")

convert_vars <- function(df, factor_vars) {
  df %>%
    mutate(across(-ID, as.numeric)) %>%
    mutate(across(all_of(factor_vars), as.factor))
}

cessationtrain_p05_final <- convert_vars(cessationtrain_p05_final, factor_vars_p05)
cessationtest_p05_final  <- convert_vars(cessationtest_p05_final,  factor_vars_p05)

dfs <- c(
  "cessationtrain_p05_final",
  "cessationtest_p05_final"
)

for (df in dfs) {
  QuA1Rc_df <- get(df)
  if ("QuA1Rc" %in% colnames(QuA1Rc_df)) {
    QuA1Rc_df$QuA1Rc <- factor(QuA1Rc_df$QuA1Rc, levels = c("1", "2"), labels = c("X1", "X2"))
  }
  assign(df, QuA1Rc_df)
}
```

#Manual Folds for Repeated 5-fold Cross-Validation
```{r}
identical(cessationtrain_p05_final$ID, cessationtrain_p05_final$ID) #TRUE

y_p05 <- factor(cessationtrain_p05_final$QuA1Rc)
y_p05 <- factor(cessationtrain_p05_final$QuA1Rc)

set.seed(843)
manual_folds_p05 <- createMultiFolds(y = y_p05, k = 5, times = 5)
names(manual_folds_p05)
str(manual_folds_p05[[1]]) 
```

#Log Ridge Recipes
```{r}
log_ridge_recipe_p05 <- recipe(QuA1Rc ~ ., data = cessationtrain_p05_final) %>%
  update_role(ID, new_role = "ID") %>% 
  update_role(row_id, new_role = "ID") %>%
  step_impute_mode(all_nominal_predictors()) %>%  
  step_impute_median(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors(), one_hot = FALSE)
```

#Log Ridge (p < 0.05)
*Training*
```{r}
n_fold <- 5
n_repeat <- 5
n_tune <- 101
n_resample <- n_fold * n_repeat

set.seed(seed)
seeds <- vector("list", length = n_resample + 1)
for (i in seq_len(n_resample)) {
  seeds[[i]] <- sample.int(1e6, n_tune)
}
seeds[[n_resample + 1]] <- sample.int(1e6, 1)

train_ctrl <- trainControl(
  method = "repeatedcv",       
  index = manual_folds_p05,           
  seeds = seeds,               
  classProbs = TRUE,
  summaryFunction = prSummary,
  savePredictions = "all"
)

set.seed(seed)
log_ridge_p05 <- train(
  log_ridge_recipe_p05,
  data = cessationtrain_p05_final,
  method = "glmnet",
  metric = "F",
  trControl = train_ctrl, 
  tuneGrid = expand.grid(
    alpha = 0,      
    lambda = c(seq(0.1, 10, by=0.1))),
  family = "binomial"
)

print(log_ridge_p05$bestTune)
log_ridge_p05_best_predict <- subset(log_ridge_p05$pred, lambda == log_ridge_p05$bestTune$lambda)
log_ridge_p05_predict <- subset(log_ridge_p05$pred)
log_ridge_p05_resample <- log_ridge_p05$resample
confusionMatrix(log_ridge_p05_best_predict$pred, log_ridge_p05_best_predict$obs)
log_ridge_p05_final_model <- log_ridge_p05$finalModel
print(log_ridge_p05_final_model)
log_ridge_p05_result <- log_ridge_p05$results

#check fold
subset(log_ridge_p05$pred, Resample == "Fold1.Rep1")

#explore coefficients and lambda trade-off
plot(log_ridge_p05_final_model, xvar="lambda",label=TRUE)
plot(log_ridge_p05)
```

*Fitting*
```{r}
train_ctrl <- trainControl(
  method = 'none',
  classProbs = TRUE,
  summaryFunction = prSummary,
  savePredictions = "all"
)

set.seed(seed)
log_ridge_final_p05 <- train(
  log_ridge_recipe_p05,
  data = cessationtrain_p05_final,
  method = "glmnet",
  metric = "F",
  trControl = train_ctrl, 
  tuneGrid = expand.grid(
    alpha = 0,      
    lambda = c(0.1)),
  family = "binomial"
)

log_ridge_final_p05_final_model <- log_ridge_final_p05$finalModel
plot(log_ridge_final_p05_final_model, xvar="lambda",label=TRUE)
```

*Testing*
```{r}
log_ridge_p05_train_predict <- predict(log_ridge_final_p05, newdata = cessationtrain_p05_final)
log_ridge_p05_test_predict <- predict(log_ridge_final_p05, newdata = cessationtest_p05_final)

confusionMatrix(log_ridge_p05_train_predict, cessationtrain_p05_final$QuA1Rc)
confusionMatrix(log_ridge_p05_test_predict, cessationtest_p05_final$QuA1Rc)
```

*Graphs and Tables*
```{r}
train_probs <- predict(log_ridge_final_p05, newdata = cessationtrain_p05_final, type = "prob")[, "X1"]
test_probs <- predict(log_ridge_final_p05, newdata = cessationtest_p05_final, type = "prob")[, "X1"]

train_obs <- factor(cessationtrain_p05_final$QuA1Rc, levels = c("X2", "X1"), labels = c("no", "yes"))
test_obs <- factor(cessationtest_p05_final$QuA1Rc, levels = c("X2", "X1"), labels = c("no", "yes"))

#calculate PR curves
pr_train <- pr.curve(scores.class0 = train_probs[train_obs == "yes"],
                     scores.class1 = train_probs[train_obs == "no"],
                     curve = TRUE)

pr_test <- pr.curve(scores.class0 = test_probs[test_obs == "yes"],
                    scores.class1 = test_probs[test_obs == "no"],
                    curve = TRUE)

#graph training and testing PRCs
pr_train_df <- as.data.frame(pr_train$curve)
colnames(pr_train_df) <- c("Recall", "Precision", "Threshold")
pr_train_df$Set <- "Train"
pr_test_df <- as.data.frame(pr_test$curve)
colnames(pr_test_df) <- c("Recall", "Precision", "Threshold")
pr_test_df$Set <- "Test"
pr_df <- bind_rows(pr_train_df, pr_test_df)
baseline_train <- mean(pr_train_df$Precision)
baseline_test <- mean(pr_test_df$Precision)
auprc_values <- data.frame(
  Set = c("Train", "Test"),
  AUPRC = c(pr_train$auc.integral, pr_test$auc.integral)
)

ggplot(pr_df, aes(x = Recall, y = Precision, color = Set)) +
  geom_line(size = 1.2) +
  geom_hline(yintercept = baseline_train, linetype = "dashed", color = "blue") +
  geom_hline(yintercept = baseline_test, linetype = "dashed", color = "red") +
  annotate("text", x = 0.01, y = baseline_train + 0.02, label = "Train Baseline", 
           hjust = 0, color = "blue", size = 4) +
  annotate("text", x = 0.01, y = baseline_test + 0.02, label = "Test Baseline", 
           hjust = 0, color = "red", size = 4) +
  scale_color_manual(values = c("Train" = "blue", "Test" = "red")) +
  labs(
    title = "LogRidge Precision-Recall Curves: Train vs. Test",
    subtitle = paste0("Train AUPRC = ", round(pr_train$auc.integral, 2),
                      ", Test AUPRC = ", round(pr_test$auc.integral, 2)),
    y = "Precision",
    x = "Recall",
    color = "Data Split"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    plot.title = element_text(face = "bold")
  )

#table of AUCs by resampling
log_ridge_p05_auprc <- log_ridge_p05_best_predict %>%
  mutate(rep = sub(".*\\.(Rep\\d+)", "\\1", Resample))

log_ridge_p05_repeat_auprc <- log_ridge_p05_auprc %>%
  group_by(rep) %>%
  summarise(
    auprc = pr.curve(
      scores.class0 = X1[obs == "X1"],
      scores.class1 = X1[obs == "X2"],
      curve = FALSE
    )$auc.integral
  )

#feature importance
log_ridge_p05_auroc_importance <- varImp(log_ridge_final_p05)$importance

best_lambda <- log_ridge_p05$bestTune$lambda
coefs_sparse <- coef(log_ridge_final_p05$finalModel, s = best_lambda)
coefs_df <- as.data.frame(as.matrix(coefs_sparse))
coefs_df$term <- rownames(coefs_df)
colnames(coefs_df)[1] <- "estimate"
log_ridge_p05_coefficients <- coefs_df[, c("term", "estimate")]

log_ridge_p05_auprc_importance <- auprc_feature_importance(
  model = log_ridge_final_p05,
  data = cessationtrain_p05_final,
  target_col = "QuA1Rc",
  positive_class = "X1"
)
```

*Save*
```{r}
save_directory <- "~/Desktop/LV/Final_Models/LogReg_Ridge"

file_path <- file.path(save_directory, "log_ridge_p05_resample.csv")
write.csv(log_ridge_p05_resample, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_p05_auroc_importance.csv")
write.csv(log_ridge_p05_auroc_importance, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_p05_auprc_importance.csv")
write.csv(log_ridge_p05_auprc_importance, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_p05_best_predict.csv")
write.csv(log_ridge_p05_best_predict, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_p05_repeat_auprc.csv")
write.csv(log_ridge_p05_repeat_auprc, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_p05_coefficients.csv")
write.csv(log_ridge_p05_coefficients, file = file_path, row.names = FALSE)
```

#Log Ridge Weight Recipes
```{r}
cessationtrain_p05_final$case_weight <- ifelse(
  cessationtrain_p05_final$QuA1Rc == "X1", 4, 1)
cessationtest_p05_final$case_weight <- ifelse(
  cessationtest_p05_final$QuA1Rc == "X1", 4, 1)

log_ridge_weight_recipe_p05 <- recipe(QuA1Rc ~ ., data = cessationtrain_p05_final) %>%
  update_role(ID, new_role = "ID") %>% 
  update_role(row_id, new_role = "ID") %>%
  update_role(case_weight, new_role = "case weight") %>%
  step_impute_mode(all_nominal_predictors()) %>%  
  step_impute_median(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors(), one_hot = FALSE)
```

#Log Ridge Weight (p < 0.05)
*Training*
```{r}
n_fold <- 5
n_repeat <- 5
n_tune <- 101
n_resample <- n_fold * n_repeat

set.seed(seed)
seeds <- vector("list", length = n_resample + 1)
for (i in seq_len(n_resample)) {
  seeds[[i]] <- sample.int(1e6, n_tune)
}
seeds[[n_resample + 1]] <- sample.int(1e6, 1)

train_ctrl <- trainControl(
  method = "repeatedcv",       
  index = manual_folds_p05,           
  seeds = seeds,               
  classProbs = TRUE,
  summaryFunction = prSummary,
  savePredictions = "all"
)

set.seed(seed)
log_ridge_weight_p05 <- train(
  log_ridge_weight_recipe_p05,
  data = cessationtrain_p05_final,
  method = "glmnet",
  metric = "F",
  trControl = train_ctrl,
  tuneGrid = expand.grid(
    alpha = 0,
    lambda = c(seq(0.1, 10, by=0.1))),
  family = "binomial",
  weights = cessationtrain_p05_final$case_weight
)

print(log_ridge_weight_p05$bestTune)
log_ridge_weight_p05_best_predict <- subset(log_ridge_weight_p05$pred, lambda == log_ridge_weight_p05$bestTune$lambda)
log_ridge_weight_p05_predict <- subset(log_ridge_weight_p05$pred)
log_ridge_weight_p05_resample <- log_ridge_weight_p05$resample
confusionMatrix(log_ridge_weight_p05_best_predict$pred, log_ridge_weight_p05_best_predict$obs)
log_ridge_weight_p05_final_model <- log_ridge_weight_p05$finalModel
print(log_ridge_weight_p05_final_model)
log_ridge_weight_p05_result <- log_ridge_weight_p05$results

#check fold
subset(log_ridge_p05$pred, Resample == "Fold1.Rep1")

#explore coefficients and lambda trade-off
plot(log_ridge_weight_p05_final_model, xvar="lambda",label=TRUE)
plot(log_ridge_weight_p05)
```

*Fitting*
```{r}
train_ctrl <- trainControl(
  method = 'none',
  classProbs = TRUE,
  summaryFunction = prSummary,
  savePredictions = "all"
)

set.seed(seed)
log_ridge_weight_final_p05 <- train(
  log_ridge_weight_recipe_p05,
  data = cessationtrain_p05_final,
  method = "glmnet",
  metric = "F",
  trControl = train_ctrl,
  tuneGrid = expand.grid(
    alpha = 0,
    lambda = 5.8),
  family = "binomial",
  weights = cessationtrain_p05_final$case_weight
)

log_ridge_weight_final_p05_final_model <- log_ridge_weight_final_p05$finalModel
plot(log_ridge_weight_final_p05_final_model, xvar="lambda",label=TRUE)
plot(log_ridge_weight_final_p05_final_model)
```

*Testing*
```{r}
log_ridge_weight_p05_train_predict <- predict(log_ridge_weight_final_p05, newdata = cessationtrain_p05_final)
log_ridge_weight_p05_test_predict <- predict(log_ridge_weight_final_p05, newdata = cessationtest_p05_final)

confusionMatrix(log_ridge_weight_p05_train_predict, cessationtrain_p05_final$QuA1Rc)
confusionMatrix(log_ridge_weight_p05_test_predict, cessationtest_p05_final$QuA1Rc)
```

*Graphs and Tables*
```{r}
train_probs <- predict(log_ridge_weight_final_p05, newdata = cessationtrain_p05_final, type = "prob")[, "X1"]
test_probs <- predict(log_ridge_weight_final_p05, newdata = cessationtest_p05_final, type = "prob")[, "X1"]

train_obs <- factor(cessationtrain_p05_final$QuA1Rc, levels = c("X2", "X1"), labels = c("no", "yes"))
test_obs <- factor(cessationtest_p05_final$QuA1Rc, levels = c("X2", "X1"), labels = c("no", "yes"))

#calculate PR curves
pr_train <- pr.curve(scores.class0 = train_probs[train_obs == "yes"],
                     scores.class1 = train_probs[train_obs == "no"],
                     curve = TRUE)

pr_test <- pr.curve(scores.class0 = test_probs[test_obs == "yes"],
                    scores.class1 = test_probs[test_obs == "no"],
                    curve = TRUE)

#graph training and testing PRCs
pr_train_df <- as.data.frame(pr_train$curve)
colnames(pr_train_df) <- c("Recall", "Precision", "Threshold")
pr_train_df$Set <- "Train"
pr_test_df <- as.data.frame(pr_test$curve)
colnames(pr_test_df) <- c("Recall", "Precision", "Threshold")
pr_test_df$Set <- "Test"
pr_df <- bind_rows(pr_train_df, pr_test_df)
baseline_train <- mean(pr_train_df$Precision)
baseline_test <- mean(pr_test_df$Precision)
auprc_values <- data.frame(
  Set = c("Train", "Test"),
  AUPRC = c(pr_train$auc.integral, pr_test$auc.integral)
)

ggplot(pr_df, aes(x = Recall, y = Precision, color = Set)) +
  geom_line(size = 1.2) +
  geom_hline(yintercept = baseline_train, linetype = "dashed", color = "blue") +
  geom_hline(yintercept = baseline_test, linetype = "dashed", color = "red") +
  annotate("text", x = 0.01, y = baseline_train + 0.02, label = "Train Baseline", 
           hjust = 0, color = "blue", size = 4) +
  annotate("text", x = 0.01, y = baseline_test + 0.02, label = "Test Baseline", 
           hjust = 0, color = "red", size = 4) +
  scale_color_manual(values = c("Train" = "blue", "Test" = "red")) +
  labs(
    title = "LogRidge Weights Precision-Recall Curves: Train vs. Test",
    subtitle = paste0("Train AUPRC = ", round(pr_train$auc.integral, 2),
                      ", Test AUPRC = ", round(pr_test$auc.integral, 2)),
    y = "Precision",
    x = "Recall",
    color = "Data Split"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    plot.title = element_text(face = "bold")
  )

#table of AUCs by resampling
log_ridge_weight_p05_auprc <- log_ridge_weight_p05_best_predict %>%
  mutate(rep = sub(".*\\.(Rep\\d+)", "\\1", Resample))

log_ridge_weight_p05_repeat_auprc <- log_ridge_weight_p05_auprc %>%
  group_by(rep) %>%
  summarise(
    auprc = pr.curve(
      scores.class0 = X1[obs == "X1"],
      scores.class1 = X1[obs == "X2"],
      curve = FALSE
    )$auc.integral
  )

#feature importance
log_ridge_weight_p05_auroc_importance <- varImp(log_ridge_weight_final_p05)$importance

best_lambda <- log_ridge_weight_p05$bestTune$lambda
coefs_sparse <- coef(log_ridge_weight_final_p05$finalModel, s = best_lambda)
coefs_df <- as.data.frame(as.matrix(coefs_sparse))
coefs_df$term <- rownames(coefs_df)
colnames(coefs_df)[1] <- "estimate"
log_ridge_weight_p05_coefficients <- coefs_df[, c("term", "estimate")]

log_ridge_weight_p05_auprc_importance <- auprc_feature_importance(
  model = log_ridge_weight_final_p05,
  data = cessationtrain_p05_final,
  target_col = "QuA1Rc",
  positive_class = "X1"
)
```

*Save*
```{r}
save_directory <- "~/Desktop/LV/Final_Models/LogReg_Ridge_Weighted"

file_path <- file.path(save_directory, "log_ridge_weight_p05_resample.csv")
write.csv(log_ridge_weight_p05_resample, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_weight_p05_auroc_importance.csv")
write.csv(log_ridge_weight_p05_auroc_importance, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_weight_p05_auprc_importance.csv")
write.csv(log_ridge_weight_p05_auprc_importance, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_weight_p05_best_predict.csv")
write.csv(log_ridge_weight_p05_best_predict, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_weight_p05_repeat_auprc.csv")
write.csv(log_ridge_weight_p05_repeat_auprc, file = file_path, row.names = FALSE)

file_path <- file.path(save_directory, "log_ridge_weight_p05_coefficients.csv")
write.csv(log_ridge_weight_p05_coefficients, file = file_path, row.names = FALSE)
```
