---
title: "Smoking Cessation Analysis: Internal Consistency"
author: "Zoë E. Laky"
date: "16JUL2023"
output: html_notebook
---

## Installing & Loading Packages (Part 3)
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/LV/Final_Data")

required_packages <- c('lavaan', 'psych', 'sjPlot', 'sjmisc', 'parameters', 'semTools', 'MBESS', 'parallel')

#install new packages
new_packages <- setdiff(required_packages, rownames(installed.packages()))
if (length(new_packages)) install.packages(new_packages)

#load packages
invisible(lapply(required_packages, require, character.only = TRUE))

#citations
sapply(c("tidyverse", "caret", "sjPlot"), citation)

#working directory
cat("Working Directory:", getwd(), "\n")
sessionInfo()
detectCores()

rm(required_packages, new_packages)
```

## Loading Data
```{r}
cessationC1 <- read.csv("LVDATA_FULL_8.11.19.csv", header = T, na.strings = "", stringsAsFactors = T) #importing data
```

## Cronbach's Alpha 

**FTND**
```{r}
FTND <- find_var(cessationC1, pattern = "FTND", out = "df")
set.seed(843)
alpha(FTND[, 1:6], na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.5730742, 278, p.val=.05, n.var=6))
alpha(FTND[, 8:13], na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #follow-up
print(alpha.ci(0.6299569, 278, p.val=.05, n.var=6))
```

**SSS**
```{r}
SSS <- find_var(cessationC1, pattern = "SSS", out = "df") #report as KR20
set.seed(843)
alpha(SSS[, 1:40], na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.7883742, 278, p.val=.05, n.var=40))
```

**SSEQ**
```{r}
SSEQ <- find_var(cessationC1, pattern = "SSEQ", out = "df") #conditional responses
SSEQ <- subset(SSEQ, select = -c(SSEQ_Answered, SSEQ_Total, SSEQ_Answered_FU, SSEQ_Total_FU))

for (i in seq(1, 33, 2)) { #loop for SSEQ baseline
  j <- i + 1 #j is i (number beginning with 1) +1
  base <- paste("SSEQ", i, sep = "") #creates label "base" (SSEQ with 1)
  followup <- paste("SSEQ", j, sep = "") #creates label "follow-up" (SSEQ starting with 2)
  followup <- paste(followup, "1", sep = "_") #creates label "follow-up" (SSEQ starting with 2 plus underscore 1)
  output <- paste("SSEQ", j, sep="") #crates label "output" (SSEQ starting with 2)
  output <- paste(output, "BRc", sep = "") #crates label "output" (SSEQ starting with 2 plus Rc)

  SSEQ[[output]] <- ifelse(SSEQ[[base]]==1 & !is.na(SSEQ[[base]]), SSEQ[[followup]], NA)
  SSEQ[[output]][SSEQ[[base]]==2] <- 0
  SSEQ[[output]][SSEQ[[base]]==3] <- NA
}

basecheck <- SSEQ[ , c("SSEQ1", "SSEQ2_1", "SSEQ2BRc")] 
table(basecheck$SSEQ1, basecheck$SSEQ2BRc, useNA='always')

for (i in seq(1, 33, 2)) { #loop for SSEQ follow-up
  j <- i + 1 
  base <- paste("SSEQ", i, sep = "") 
  base <- paste(base, "FU", sep = "_") 
  followup <- paste("SSEQ", j, sep = "") 
  followup <- paste(followup, "1_FU", sep = "_") 
  output <- paste("SSEQ", j, sep="") 
  output <- paste(output, "FRc", sep = "")

  SSEQ[[output]] <- ifelse(SSEQ[[base]]==1 & !is.na(SSEQ[[base]]), SSEQ[[followup]], NA)
  SSEQ[[output]][SSEQ[[base]]==2] <- 0
  SSEQ[[output]][SSEQ[[base]]==3] <- NA
}

follcheck <- SSEQ[ , c("SSEQ1_FU", "SSEQ2_1_FU", "SSEQ2FRc")] 
table(follcheck$SSEQ1_FU, follcheck$SSEQ2FRc, useNA='always')

set.seed(843)
SSEQb <- find_var(SSEQ, pattern = "BRc", out = "df") 
alpha(SSEQb[, 1:17], na.rm=TRUE, n.iter=1000, delete=TRUE, use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.9286844, 278, p.val=.05, n.var=17))

SSEQf <- find_var(SSEQ, pattern = "FRc", out = "df") 
alpha(SSEQf[, 1:17], na.rm=TRUE, n.iter=1000, delete=TRUE, use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #follow-up
print(alpha.ci(0.9416277, 278, p.val=.05, n.var=17))

rm(SSEQ, basecheck, follcheck)
```

**CSCLS**
```{r}
CSCLS <- find_var(cessationC1, pattern = "CSCLS", out = "df")
set.seed(843)
alpha(CSCLS[, 1:12], na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.9385761, 278, p.val=.05, n.var=12))
```

**PRBQ**
```{r}
set.seed(843)
PRBQbb <- cessationC1[, c("PRBQ2", "PRBQ3", "PRBQ4", "PRBQ5", "PRBQ6", "PRBQ7", "PRBQ9", "PRBQ12", "PRBQ16", "PRBQ17", "PRBQ18", "PRBQ22", "PRBQ24", "PRBQ25", "PRBQ27", "PRBQ29", "PRBQ31", "PRBQ32", "PRBQ35", "PRBQ36", "PRBQ38", "PRBQ40")]
alpha(PRBQbb, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.9315411, 278, p.val=.05, n.var=22))

PRBQbf <- cessationC1[, c("PRBQ2_FU", "PRBQ3_FU", "PRBQ4_FU", "PRBQ5_FU", "PRBQ6_FU", "PRBQ7_FU", "PRBQ9_FU", "PRBQ12_FU", "PRBQ16_FU", "PRBQ17_FU", "PRBQ18_FU", "PRBQ22_FU", "PRBQ24_FU", "PRBQ25_FU", "PRBQ27_FU", "PRBQ29_FU", "PRBQ31_FU", "PRBQ32_FU", "PRBQ35_FU", "PRBQ36_FU", "PRBQ38_FU", "PRBQ40_FU")]
alpha(PRBQbf, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #follow-up
print(alpha.ci(0.9266207, 278, p.val=.05, n.var=22))

PRBQrb <- cessationC1[, c("PRBQ1", "PRBQ8", "PRBQ10", "PRBQ11", "PRBQ13", "PRBQ14", "PRBQ15", "PRBQ19",  "PRBQ20", "PRBQ21", "PRBQ23", "PRBQ26", "PRBQ28", "PRBQ30", "PRBQ33", "PRBQ34", "PRBQ37", "PRBQ39")]
alpha(PRBQrb, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.865744, 278, p.val=.05, n.var=18))

PRBQrf <- cessationC1[, c("PRBQ1_FU", "PRBQ8_FU", "PRBQ10_FU", "PRBQ11_FU", "PRBQ13_FU", "PRBQ14_FU", "PRBQ15_FU", "PRBQ19_FU", "PRBQ20_FU", "PRBQ21_FU", "PRBQ23_FU", "PRBQ26_FU", "PRBQ28_FU", "PRBQ30_FU", "PRBQ33_FU", "PRBQ34_FU", "PRBQ37_FU", "PRBQ39_FU")]
alpha(PRBQrf, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #follow-up
print(alpha.ci(0.8899488, 278, p.val=.05, n.var=18))

rm(PRBQbb, PRBQbf, PRBQrb, PRBQrf)
```

**SCQ**
```{r}
set.seed(843)
SCQbb <- cessationC1[, c("SCQ1", "SCQ2", "SCQ4", "SCQ5", "SCQ6", "SCQ7", "SCQ9", "SCQ10", "SCQ11", "SCQ12", "SCQ13", "SCQ15", "SCQ16", "SCQ17", "SCQ18", "SCQ19", "SCQ20", "SCQ21", "SCQ22", "SCQ23", "SCQ26", "SCQ27", "SCQ28", "SCQ29", "SCQ31", "SCQ32", "SCQ33", "SCQ35", "SCQ37", "SCQ38", "SCQ40", "SCQ41", "SCQ42", "SCQ44", "SCQ45", "SCQ47", "SCQ48", "SCQ49", "SCQ50", "SCQ51", "SCQ52", "SCQ53", "SCQ54")]
alpha(SCQbb, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.9538951, 278, p.val=.05, n.var=43))

SCQbf <- cessationC1[, c("SCQ1_FU", "SCQ2_FU", "SCQ4_FU", "SCQ5_FU", "SCQ6_FU", "SCQ7_FU", "SCQ9_FU", "SCQ10_FU", "SCQ11_FU", "SCQ12_FU", "SCQ13_FU", "SCQ15_FU", "SCQ16_FU", "SCQ17_FU", "SCQ18_FU", "SCQ19_FU", "SCQ20_FU", "SCQ21_FU", "SCQ22_FU", "SCQ23_FU", "SCQ26_FU", "SCQ27_FU", "SCQ28_FU", "SCQ29_FU", "SCQ31_FU", "SCQ32_FU", "SCQ33_FU", "SCQ35_FU", "SCQ37_FU", "SCQ38_FU", "SCQ40_FU", "SCQ41_FU", "SCQ42_FU", "SCQ44_FU", "SCQ45_FU", "SCQ47_FU", "SCQ48_FU", "SCQ49_FU", "SCQ50_FU", "SCQ51_FU", "SCQ52_FU", "SCQ53_FU", "SCQ54_FU")]
alpha(SCQbf, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #follow-up
print(alpha.ci(0.9632229, 278, p.val=.05, n.var=43))

SCQrb <- cessationC1[, c("SCQ3", "SCQ8", "SCQ14", "SCQ24", "SCQ25", "SCQ30", "SCQ34", "SCQ36", "SCQ39", "SCQ43", "SCQ46", "SCQ55")] 
alpha(SCQrb, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.7986049, 278, p.val=.05, n.var=12))

SCQrf <- cessationC1[, c("SCQ3_FU", "SCQ8_FU", "SCQ14_FU", "SCQ24_FU", "SCQ25_FU", "SCQ30_FU", "SCQ34_FU", "SCQ36_FU", "SCQ39_FU", "SCQ43_FU", "SCQ46_FU", "SCQ55_FU")] 
alpha(SCQrf, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #follow-up
print(alpha.ci(0.8326241, 278, p.val=.05, n.var=12))

rm(SCQbb, SCQbf, SCQrb, SCQrf)
```

**VVIQ**
```{r}
set.seed(843)
VVIQo <- cessationC1[, c("VVIQ1_1", "VVIQ2_1", "VVIQ3_1", "VVIQ4_1", "VVIQ5_1", "VVIQ6_1", "VVIQ7_1", "VVIQ8_1", "VVIQ9_1", "VVIQ10_1", "VVIQ11_1", "VVIQ12_1", "VVIQ13_1", "VVIQ14_1", "VVIQ15_1", "VVIQ16_1")]
alpha(VVIQo, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.9375246, 278, p.val=.05, n.var=16))

VVIQc <- cessationC1[, c("VVIQ1_2", "VVIQ2_2", "VVIQ3_2", "VVIQ4_2", "VVIQ5_2", "VVIQ6_2", "VVIQ7_2", "VVIQ8_2", "VVIQ9_2", "VVIQ10_2", "VVIQ11_2", "VVIQ12_2", "VVIQ13_2", "VVIQ14_2", "VVIQ15_2", "VVIQ16_2")]
alpha(VVIQc, na.rm=TRUE, n.iter=1000, delete=TRUE,use="pairwise", warnings=TRUE, n.obs=NULL,impute=NULL) #baseline
print(alpha.ci(0.9380395, 278, p.val=.05, n.var=16))

set.seed(NULL)
```
